### ISSUE TITLE
Issue in part e 

### ISSUE THREAD

**Issue by taraobyrne** [jameslamb/teaching#10]
findMin(rep(10:20))                 # should return 10
**findMin(c(-5, 10, 100))             # should return -5**
findMin(c(1:10, 20:50, 0.999, 6))   # should return 0.999

The above is what was given to us in D2L. 

In class, the second row showed
findMin(c(-5, 10, 100, -8))             # should return -8   ----> -8 is missing in D2L

**Comment by jameslamb** [comment]
Thanks @taraobyrne for creating this and for the details!

I just updated the one on D2L. I know that doesn't help yall very much, but it will help future classes!
