### ISSUE TITLE
new devtools deprecated functions Re:Week 5 Programming Supplement

### ISSUE THREAD

**Issue by amysheep** [jameslamb/teaching#14]
Nice tutorial!

Deprecated and currently in your material:
devtools::create
DESCRIPTION file has a slightly different look now

Add usethis::use_testthat() to generate the testthat folder

New calls:
usethis::create_package

**Comment by jameslamb** [comment]
hey thanks @amysheep !

**Comment by jameslamb** [comment]
for my own reference when I come back to fix this, this refers to https://github.com/jameslamb/teaching/blob/master/mu_rprog/code/Week5_Supplement.Rmd
